import express from "express";
import auth_router from "./auth/routes/auth.routes.js";
import quests_router from "./quests/routes/quests.routes.js";
import quiz_router from "./quiz/routes/quiz.routes.js";
import cors from 'cors';
const app= express();
app.use(express.json());
app.use(cors());
app.use("/auth", auth_router);
app.use("/quests", quests_router);
app.use("/quiz", quiz_router);
export default app;
